version: 2
jobs:
  build:
    working_directory: ~/sklearn-dummies
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest --cov
      - run: codecov --token=16bfbcfe-9f93-4b04-852a-8a695b762fc0
