version: 2
jobs:
  build:
    working_directory: ~/sklearn-dummies
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python setup.py install
            pytest --cov sklearn_dummies
            bash <(curl -s https://codecov.io/bash)
